### ISSUE TITLE
latest update of service framework caused and error on Runtime Node

### ISSUE THREAD

**Issue by jboulmal** [reTHINK-project/dev-service-framework#56]
Hi,
After updating the core-runtime and service framework `npm update`. We have got a blocking error on Runtime Node.
```
~/dev-runtime-nodejs/node_modules/service-framework/dist/PersistenceManager.js:29
if(!o(e)||e<0||isNaN(e))throw TypeError("n must be a positive number");return this._maxListeners=e,this},r.prototype.emit=function(e){var t,n,r,o,u,f;if(this._events||(this._events={}),"error"===e&&(!this._events.error||s(this._events.error)&&!this._events.error.length)){if(t=arguments[1],t instanceof Error)throw t;var c=new Error('Uncaught, unspecified "error" event. ('+t+")");throw c.context=t,c}if(n=this._events[e],a(n))return!1;if(i(n))switch(arguments.length){case 1:n.call(this);break;case 2:n.call(this,arguments[1]);break;case 3:n.call(this,arguments[1],arguments[2]);break;default:o=Array.prototype.slice.call(arguments,1),n.apply(this,o)}else if(s(n))for(o=Array.prototype.slice.call(arguments,1),f=n.slice(),r=f.length,u=0;u<r;u++)f[u].apply(this,o);return!0},r.prototype.addListener=function(e,t){var n;if(!i(t))throw TypeError("listener must be a function");return this._events||(this._events={}

TypeError: Cannot read property 'prototype' of undefined
    at i (~/dev-runtime-nodejs/node_modules/service-framework/dist/PersistenceManager.js:29:5594)
    at Object.<anonymous> (~/dev-runtime-nodejs/node_modules/service-framework/dist/PersistenceManager.js:29:6274)
    at Object.r.14../fs.js (~/dev-runtime-nodejs/node_modules/service-framework/dist/PersistenceManager.js:29:6617)
    at i (~/dev-runtime-nodejs/node_modules/service-framework/dist/PersistenceManager.js:28:561)
    at ~/dev-runtime-nodejs/node_modules/service-framework/dist/PersistenceManager.js:28:612
    at Object.<anonymous> (~/dev-runtime-nodejs/node_modules/service-framework/dist/PersistenceManager.js:30:22083)
    at Object.r.45._process (~/dev-runtime-nodejs/node_modules/service-framework/dist/PersistenceManager.js:30:22606)
    at i (~/dev-runtime-nodejs/node_modules/service-framework/dist/PersistenceManager.js:28:561)
    at ~/node_modules/service-framework/dist/PersistenceManager.js:28:612
    at Object.<anonymous> (~/dev-runtime-nodejs/node_modules/service-framework/dist/PersistenceManager.js:29:14187)
```
```Package.json :```
"runtime-core": "github:rethink-project/dev-runtime-core#develop",
"service-framework": "github:rethink-project/dev-service-framework#develop"

**Comment by pchainho** [comment]
should be fixed. reopen if needed
