### ISSUE TITLE
Latest updates on develop throwing error on nodejs-runtime

### ISSUE THREAD

**Issue by jboulmal** [reTHINK-project/dev-service-framework#97]
Hello,
Recently, We have got the following error while loading (`latest runtime`)  from toolkit on `develop` branch.
```
➜  dev-runtime-nodejs git:(develop-constraints) npm run demo

> runtime-nodejs@0.1.0 demo ~/dev-runtime-nodejs
> npm run build && node dist/demo.js


> runtime-nodejs@0.1.0 build ~/dev-runtime-nodejs
> shx mkdir -p dist/ && babel --presets es2015 src/ demo/ --out-dir dist/ && babel --presets es2015 demo/ -o dist/HelloWorldObserver.js

src/ContextApp.js -> dist/ContextApp.js
src/ContextServiceProvider.js -> dist/ContextServiceProvider.js
src/Request.js -> dist/Request.js
src/RuntimeCapabilities.js -> dist/RuntimeCapabilities.js
src/RuntimeFactory.js -> dist/RuntimeFactory.js
src/RuntimeNode.js -> dist/RuntimeNode.js
src/SandboxApp.js -> dist/SandboxApp.js
src/SandboxWorker.js -> dist/SandboxWorker.js
src/core.js -> dist/core.js
demo/demo.js -> dist/demo.js
Node http Request
getting descriptor from: https://catalogue.localhost/.well-known/runtime/Runtime
constraints: undefined
HTTPS Request: GET https://catalogue.localhost/.well-known/runtime/Runtime/version undefined
Mapped url is  https://catalogue.localhost/.well-known/runtime/Runtime/version method is: GET
HTTPS Request: GET https://catalogue.localhost/.well-known/runtime/Runtime/cguid undefined
Mapped url is  https://catalogue.localhost/.well-known/runtime/Runtime/cguid method is: GET
adding promise to attach sourcePackage
{ Error
    at createNonNativeDOMExceptionClass (~/dev-runtime-nodejs/node_modules/indexeddbshim/dist/indexeddbshim-node.js:8776:35)
    at Object.324../CFG (~/dev-runtime-nodejs/node_modules/indexeddbshim/dist/indexeddbshim-node.js:8837:33)
    at s (~/dev-runtime-nodejs/node_modules/indexeddbshim/dist/indexeddbshim-node.js:1:692)
    at ~/dev-runtime-nodejs/node_modules/indexeddbshim/dist/indexeddbshim-node.js:1:743
    at Object.333../DOMException (~/dev-runtime-nodejs/node_modules/indexeddbshim/dist/indexeddbshim-node.js:12296:21)
    at s (~/dev-runtime-nodejs/node_modules/indexeddbshim/dist/indexeddbshim-node.js:1:692)
    at ~/dev-runtime-nodejs/node_modules/indexeddbshim/dist/indexeddbshim-node.js:1:743
    at Object.327../CFG (~/dev-runtime-nodejs/node_modules/indexeddbshim/dist/indexeddbshim-node.js:9192:19)
    at s (~/dev-runtime-nodejs/node_modules/indexeddbshim/dist/indexeddbshim-node.js:1:692)
    at ~/dev-runtime-nodejs/node_modules/indexeddbshim/dist/indexeddbshim-node.js:1:743
  _code: 18,
  _name: 'SecurityError',
  _message: 'Cannot open an IndexedDB database from an opaque origin.',
  code: 18,
  name: 'SecurityError' }
statusCode is:  200
statusCode is:  200
got version (11.299999999999976) and cguid (3-59cc6223-b0de-9c8a-6290-5eed257a7b9f0) for descriptor https://catalogue.localhost/.well-known/runtime/Runtime
[StorageManager] - getVersion for key  3-59cc6223-b0de-9c8a-6290-5eed257a7b9f0
error getting the version for  3-59cc6223-b0de-9c8a-6290-5eed257a7b9f0  with error:  { OpenFailedError: SecurityError Cannot open an IndexedDB database from an opaque origin.
    at StorageManager.getVersion (~/dev-runtime-nodejs/node_modules/service-framework/dist/StorageManager.js:303:81)
  _e: 
   Error
       at getErrorWithStack (~/dev-runtime-nodejs/node_modules/dexie/dist/dexie.js:321:12)
       at new DexieError (~/dev-runtime-nodejs/node_modules/dexie/dist/dexie.js:450:19)
       at Transaction.Dexie.props.create (~/dev-runtime-nodejs/node_modules/dexie/dist/dexie.js:2897:31)
       at tempTransaction (~/dev-runtime-nodejs/node_modules/dexie/dist/dexie.js:1846:23)
       at Table.getTransaction (~/dev-runtime-nodejs/node_modules/dexie/dist/dexie.js:2346:17)
       at Table.getIDBObjectStore (~/dev-runtime-nodejs/node_modules/dexie/dist/dexie.js:2357:25)
       at Collection._read (~/dev-runtime-nodejs/node_modules/dexie/dist/dexie.js:3496:31)
       at Collection.toArray (~/dev-runtime-nodejs/node_modules/dexie/dist/dexie.js:3577:29)
       at Collection.first (~/dev-runtime-nodejs/node_modules/dexie/dist/dexie.js:3666:38)
       at StorageManager.getVersion (~/dev-runtime-nodejs/node_modules/service-framework/dist/StorageManager.js:303:81),
  name: 'OpenFailedError',
  message: 'SecurityError Cannot open an IndexedDB database from an opaque origin.',
  inner: 
   { Error
       at createNonNativeDOMExceptionClass (~/dev-runtime-nodejs/node_modules/indexeddbshim/dist/indexeddbshim-node.js:8776:35)
```

In order to  reproduce the above error :
> dev-hyeprty-toolkit (`develop`) = `npm run start:all`
> dev-runtime-nodejs (`develop` or `develop-constraints`) = `npm run setup` then `npm run demo`

**Comment by Trikolon** [comment]
Please prioritize this issue. We need it fixed for our demo deployment. See https://github.com/reTHINK-project/dev-runtime-nodejs/issues/21

**Comment by emmelmann-fokus** [comment]
@pchainho could you assist in progressing this issue, please.

**Comment by pchainho** [comment]
lets fix this next week in the integration meeting

**Comment by jboulmal** [comment]
Problem solved in Aveiro integration.
